[profile.release]
panic = "unwind"

[workspace]
members = [
    "bot",
    "bounty-pallet",
    "client",
    "demo",
    "node",
    "runtime",
]

[patch.crates-io]
substrate-subxt = { git = "https://github.com/dvc94ch/substrate-subxt", branch = "different-assert" }
